package sample.controller;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;
import sample.dao.AppointmentsDAO;
import sample.dao.CountriesDAO;
import sample.dao.CustomersDAO;
import sample.dao.DivisionsDAO;
import sample.model.Appointments;
import sample.model.Countries;
import sample.model.Customers;
import sample.model.Divisions;

import java.io.IOException;
import java.net.URL;
import java.sql.SQLException;
import java.util.*;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * This class is responsible for managing the customer information screen.
 * It retrieves and sets all customer data and handles customer selection.
 */
public class CustomerCont implements Initializable {

    CustomerCont customerCont;

    private AtomicBoolean isUpdating = new AtomicBoolean(false);

    private Divisions selectedDivision;

    private Countries selectedCountry;

    private ObservableList<Divisions> allDivisions;

    private ObservableList<Countries> allCountries;

    private ObservableList<Divisions> filteredDivisions = FXCollections.observableArrayList();

    private ObservableList<Appointments> allAppointments = FXCollections.observableArrayList();

    @FXML
    private TableColumn<Customers, String> addressCol;

    @FXML
    private TextField addressTxt;

    @FXML
    private TableColumn<Customers, Integer> countryIdCol;

    @FXML
    private TableView<Customers> customerTV;

    @FXML
    private TableColumn<Customers, Integer> idCol;

    @FXML
    private TextField idTxt;

    @FXML
    private Button menuBtt;

    @FXML
    private TableColumn<Customers, String> nameCol;

    @FXML
    private TextField nameTxt;

    @FXML
    private TableColumn<Customers, String> phoneCol;

    @FXML
    private TextField phoneTxt;

    @FXML
    private TableColumn<Customers, String> postalCol;

    @FXML
    private TextField postalTxt;

    @FXML
    private ComboBox<Divisions> divisionCB = new ComboBox<Divisions>();

    @FXML
    private TableColumn<Customers, Integer> divisionIdCol;

    @FXML
    private ComboBox<Countries> countryCB;

    /**
     * Handles the event when the country combo box selection changes.
     * Updates the selected country, filtered divisions, and division combo box based on the selected country.
     * Clears and updates the division combo box items.
     * This method is triggered by an action event from the country combo box.
     *
     * @param event The action event generated by the country combo box.
     */
    @FXML
    void countryCBAction(ActionEvent event) {
        if (!isUpdating.get()){
            System.out.println("Country CBAction engaged after isUpdating check");
            isUpdating.set(true);
            for (Countries country : allCountries) {
                if (country.equals(countryCB.getSelectionModel().getSelectedItem())) {
                    selectedCountry = country;
                }
            }
            if (selectedDivision != null && !selectedDivision.getCountryId().equals(selectedCountry.getCountryId())) {
                selectedDivision = null;
                divisionCB.getSelectionModel().select(selectedDivision);
            }
            divisionCB.getItems().clear();
            filteredDivisions.clear();
            if (selectedCountry != null) {
                for (Divisions div : allDivisions) {
                    if (div.getCountryId().equals(selectedCountry.getCountryId())) {
                        filteredDivisions.add(div);
                    }
                }
            }
            divisionCB.getItems().addAll(filteredDivisions);
            divisionCB.getSelectionModel().select(selectedDivision);
        }
        isUpdating.set(false);
    }

    /**
     * Handles the event when the division combo box selection changes.
     * Updates the selected division based on the selected item in the division combo box.
     * This method is triggered by an action event from the division combo box.
     *
     * @param event The action event generated by the division combo box.
     */
    @FXML
    void divisionCBAction(ActionEvent event) {
        if (!isUpdating.get()){
            System.out.println("Division CBAction engaged after isUpdating check");
            isUpdating.set(true);
            for (Divisions div : allDivisions) {
                if (div.equals(divisionCB.getSelectionModel().getSelectedItem())) {
                    selectedDivision = div;
                }
            }
        }
        isUpdating.set(false);
    }

    /**
     * Sets all divisions by retrieving them from the database using DivisionsDAO.
     * Updates the list of all divisions and populates the division combo box with the divisions.
     *
     */
    public void setAllDivisions() throws SQLException {
        DivisionsDAO.setAllDivisions();
        allDivisions = DivisionsDAO.getAllDivisions();
        divisionCB.getItems().addAll(allDivisions);
    }

    /**
     * Sets all countries by retrieving them from the database using CountriesDAO.
     * Updates the list of all countries and populates the country combo box with the countries.
     *
     */
    public void setAllCountries() throws SQLException{
        CountriesDAO.setAllCountries();
        allCountries = CountriesDAO.getAllCountries();
        countryCB.getItems().addAll(allCountries);
    }

    /**
     * Displays an information alert dialog with the specified title, header text, and content text.
     *
     * @param title       the title of the alert dialog.
     * @param headerText  the header text of the alert dialog.
     * @param contentText the content text of the alert dialog.
     */
    static void alertInfo(String title, String headerText, String contentText){
        Alert alert = new Alert(Alert.AlertType.INFORMATION);
        alert.setTitle(title);
        alert.setHeaderText(headerText);
        alert.setContentText(contentText);
        alert.showAndWait();
    }

    /**
     * Handles the action event for the add button.
     * Attempts to add a new customer using the input fields' values.
     * Displays appropriate error messages if there are any exceptions or invalid input.
     *
     * @param event the action event that triggered the method.
     */
    @FXML
    void addAction(ActionEvent event) throws RuntimeException {
        try {
            String name = nameTxt.getText();
            String address = addressTxt.getText();
            String postalCode = postalTxt.getText();
            String phone = phoneTxt.getText();
            System.out.println("Start of add method checks!");
            Integer divisionId = selectedDivision.getDivisionId();
            Integer countryId = selectedDivision.getCountryId();

            Customers parsedCustomer = new Customers(name, address, postalCode, phone, divisionId, countryId);
            System.out.println("Object constructed");

            CustomersDAO.addCustomer(parsedCustomer);
            customerTV.getItems().clear();
            CustomersDAO.setAllCustomers();
            customerTV.setItems(CustomersDAO.getAllCustomers());
            customerTV.refresh();
        } catch (ClassCastException e) {
            System.out.println("Class Cast Exception caught in add action");
            alertInfo("Class Cast Exception", "Division ID and Country ID do not match", "Please enter a Country and Division ID that match");
        } catch (SQLException e){
            System.out.println("SQL Exception caught in add action");
            alertInfo("SQL Exception", "Input data does not match the correct data type", "Please use the correct units for data");
        }
    }

    /**
     * Handles the action event for the delete button.
     * Deletes the selected customer after checking if they have any appointments.
     * Refreshes the customer table view and displays appropriate alert messages.
     *
     * @param event the action event that triggered the method.
     */
    @FXML
    void deleteAction(ActionEvent event) throws SQLException {
        Customers selectedCustomer = customerTV.getSelectionModel().getSelectedItem();

        for (Appointments thisAppointment : allAppointments){
            if (thisAppointment.getCustomerId() == selectedCustomer.getCustomerId()){
                alertInfo("Error", "This customer still has appointments", "Delete this customer's appointments before deleting the customer");
                return;
            }
        }

        CustomersDAO.deleteCustomer(selectedCustomer);
        customerTV.getItems().clear();
        CustomersDAO.setAllCustomers();
        customerTV.setItems(CustomersDAO.getAllCustomers());
        customerTV.refresh();
        alertInfo("Warning", "Customer is deleted", "Customer is deleted");
    }

    /**
     * Handles the action event for the menu button.
     * Clears the customer table view, division combo box, and country combo box.
     * Loads the menu view and sets it as the current scene.
     *
     * @param event the action event that triggered the method.
     */
    @FXML
    void menuAction(ActionEvent event) throws IOException {
        customerTV.getItems().clear();
        divisionCB.getItems().clear();
        countryCB.getItems().clear();

        FXMLLoader loader = new FXMLLoader(getClass().getResource("/sample/view/menu.fxml"));
        Parent root = loader.load();
        Stage currentStage = (Stage) menuBtt.getScene().getWindow();
        currentStage.setScene(new Scene(root));
        currentStage.show();
    }

    /**
     * Handles the action event for the update button.
     * Updates the selected customer with the modified information from the input fields.
     * Displays appropriate error messages if there are any exceptions or invalid input.
     *
     * @param event the action event that triggered the method.
     */
    @FXML
    void updateAction(ActionEvent event) throws RuntimeException{
        try {
            int customerId = Integer.parseInt(idTxt.getText());
            String name = nameTxt.getText();
            String address = addressTxt.getText();
            String postalCode = postalTxt.getText();
            String phone = phoneTxt.getText();
            Integer divisionId = selectedDivision.getDivisionId();
            Integer countryId = selectedDivision.getCountryId();

            Customers parsedCustomer = new Customers(customerId, name, address, postalCode, phone, divisionId, countryId);
            CustomersDAO.updateCustomer(parsedCustomer);
            customerTV.getItems().clear();
            CustomersDAO.setAllCustomers();
            customerTV.setItems(CustomersDAO.getAllCustomers());
            customerTV.refresh();
        } catch (ClassCastException e){
            alertInfo("Error", "Class Cast Exception", "Please input appropriate data");
        } catch (SQLException throwables){
            alertInfo("Error", "SQL Exception", "Please input appropriate data");
        }
    }

    /**
     * Initializes the customer information screen.
     * Retrieves and sets all customer data, including countries and divisions.
     * Sets up the table view and binds its columns to customer properties.
     */
    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {



        isUpdating.set(false);

        try {
            CustomersDAO.setAllCustomers();
            AppointmentsDAO.setAllAppointments();
            allAppointments = AppointmentsDAO.getAllAppointments();
            setAllCountries();
            setAllDivisions();
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }

        customerTV.setItems(CustomersDAO.getAllCustomers());
        idCol.setCellValueFactory(new PropertyValueFactory<>("customerId"));
        nameCol.setCellValueFactory(new PropertyValueFactory<>("customerName"));
        addressCol.setCellValueFactory(new PropertyValueFactory<>("address"));
        postalCol.setCellValueFactory(new PropertyValueFactory<>("postalCode"));
        phoneCol.setCellValueFactory(new PropertyValueFactory<>("phone"));
        countryIdCol.setCellValueFactory(new PropertyValueFactory<>("countryId"));
        divisionIdCol.setCellValueFactory(new PropertyValueFactory<>("divisionId"));

        try {
            customerTV.getSelectionModel().selectedItemProperty().addListener((obsTV, oldSelectionTV, newSelectionTV) -> {
                if (newSelectionTV != null && !isUpdating.get()) {
                    isUpdating.set(true);
                    idTxt.setText(String.valueOf(newSelectionTV.getCustomerId()));
                    nameTxt.setText(String.valueOf(newSelectionTV.getCustomerName()));
                    addressTxt.setText(String.valueOf(newSelectionTV.getAddress()));
                    postalTxt.setText(String.valueOf(newSelectionTV.getPostalCode()));
                    phoneTxt.setText(String.valueOf(newSelectionTV.getPhone()));
                    for (Countries country : allCountries){
                        if (country.getCountryId().equals(newSelectionTV.getCountryId())){
                            selectedCountry = country;
                            countryCB.getSelectionModel().select(selectedCountry);
                        }
                    }
                    for (Divisions div : allDivisions) {
                        if (div.getDivisionId().equals(newSelectionTV.getDivisionId())) {
                            selectedDivision = div;
                        }
                    }
                    divisionCB.getItems().clear();
                    filteredDivisions.clear();
                    for (Divisions div : allDivisions){
                        if (div.getCountryId().equals(selectedCountry.getCountryId())){
                            filteredDivisions.add(div);
                        }
                    }
                    divisionCB.getItems().addAll(filteredDivisions);

                    divisionCB.setValue(selectedDivision);
                    divisionCB.getSelectionModel().select(selectedDivision);
                }
                isUpdating.set(false);
            });
        } catch (RuntimeException e){
            System.out.println("Caught in Table View Listener");
        }
    }
}

